#!/usr/bin/env bash
set -uo pipefail

WATCH_DIR="$HOME/.local/src/c++/aima-cpp"
FORMAT=$'\033[1;33m%w%f\033[0m written'

# Run once at startup
(
  cd "$WATCH_DIR"
  ./mm
)

# Watch recursively for common file changes
while inotifywait -r \
  -e modify,create,delete,move,attrib,close_write \
  --format "$FORMAT" \
  "$WATCH_DIR"
do
  (
    cd "$WATCH_DIR"
    ./mm
  )
done




